version: '2'
services:
  gateway-postgresql:
    container_name: postgres-gateway
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/gateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
